### ISSUE TITLE
Clean-up script triggers a delete all resource groups in subscription

### ISSUE THREAD

**Issue by cdmdotnet** [Azure-Samples/azure-logic-apps-deployment-samples#9]
I ran your `clean-up.ps1` script, which at first glance looks like it should delete only resource groups starting with the matching groupId, however the close bracket `)` of the `StartsWith` method is before the culture parameter, which for some reason powershell doesn't throw an error on and just evaluates all iterations to be true and cleans out your subscription of all resource groups.

You might want to fix that up before other people follow and or use the sample on something like a department wide development subscription, or worse, a production subscription, and cleans out everything.

Offending line
`    if ($resourceGroup.ResourceGroupName.StartsWith($groupId), 'CurrentCultureIgnoreCase') {`
Proposed fix
`    if ($resourceGroup.ResourceGroupName.StartsWith($groupId, 'CurrentCultureIgnoreCase')) {`

I have a suspicion your clean-up.ps1 script might also be in multiple sample projects.

**Comment by scgbear** [comment]
Patch merged to fix this issue
